services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    volumes:
      - app_storage:/app/storage
      - app_cache:/app/bootstrap/cache
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: railway
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
