services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: toche
      DB_USERNAME: Bernard
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: toche
      MYSQL_USER: Bernard
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"  # exposer MySQL sur le port 33061 de la machine hôte

