services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: toche
      DB_USERNAME: Bernard
      DB_PASSWORD: password
    volumes:
      - app_storage:/app/storage
      - app_cache:/app/bootstrap/cache
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toche
      MYSQL_USER: Bernard
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_storage:
  app_cache:
  db_data:
